import { db } from '@/lib/db';
import { Users, Package, FileText, ShoppingCart, Receipt, AlertTriangle, Plus } from 'lucide-react';
function money(v:any){return new Intl.NumberFormat('fr-MA',{style:'currency',currency:'MAD',maximumFractionDigits:0}).format(Number(v||0))}
export default async function Dashboard(){
 const [customers,products,quotes,orders,invoices,paid,lowStock,recent]=await Promise.all([
  db.customer.count(),db.product.count({where:{active:true}}),db.quote.count(),db.order.count(),db.invoice.count(),db.payment.aggregate({_sum:{amount:true}}),db.product.findMany({where:{stock:{lte:10},active:true},orderBy:{stock:'asc'},take:5}),db.quote.findMany({include:{customer:true},orderBy:{createdAt:'desc'},take:5})
 ]);
 const cards=[['Clients',customers,Users],['Produits',products,Package],['Devis',quotes,FileText],['Commandes',orders,ShoppingCart],['Factures',invoices,Receipt]];
 return <main className="min-h-screen flex"><aside className="sidebar w-64 p-5 hidden md:block"><div className="text-2xl font-bold mb-8">Sales<span className="text-indigo-400">ERP</span></div>{[['Dashboard','/'],['Clients','/clients'],['Produits','/produits'],['Devis','/devis'],['Commandes','/commandes'],['Factures','/factures']].map(([x,href])=><a className="nav" href={href} key={x}>{x}</a>)}</aside><section className="flex-1 p-4 md:p-8 max-w-7xl mx-auto w-full"><header className="flex justify-between items-center mb-6"><div><h1 className="text-2xl md:text-3xl font-bold">Bonjour 👋</h1><p className="muted mt-1">Pilotez vos ventes depuis n'importe où.</p></div><a className="btn btn-primary" href="/devis/nouveau"><Plus size={18}/> Nouveau devis</a></header><div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mb-5">{cards.map(([label,value,Icon]:any)=><div className="card" key={label}><Icon size={19}/><div className="muted text-xs mt-3">{label}</div><div className="text-xl font-bold mt-1">{value}</div></div>)}</div><div className="grid lg:grid-cols-3 gap-5"><div className="card lg:col-span-2"><h2 className="font-bold text-lg">Trésorerie encaissée</h2><div className="text-3xl font-bold mt-3">{money(paid._sum.amount)}</div><p className="muted text-sm mt-1">Total des paiements enregistrés</p></div><div className="card"><div className="flex items-center gap-2 mb-3"><AlertTriangle size={18}/><h2 className="font-bold">Stock faible</h2></div>{lowStock.map(p=><div className="flex justify-between py-2 border-b last:border-0" key={p.id}><span className="text-sm">{p.name}</span><b>{p.stock}</b></div>)}{!lowStock.length&&<p className="muted">Aucune alerte.</p>}</div></div><div className="card mt-5"><h2 className="font-bold text-lg mb-4">Derniers devis</h2><div className="table-wrap"><table className="w-full text-sm"><thead><tr className="text-left muted border-b"><th className="py-3">N°</th><th>Client</th><th>Statut</th><th>Total</th><th>Date</th></tr></thead><tbody>{recent.map(q=><tr className="border-b last:border-0" key={q.id}><td className="py-3 font-semibold">{q.number}</td><td>{q.customer.companyName}</td><td><span className="badge">{q.status}</span></td><td>{money(q.total)}</td><td>{q.createdAt.toLocaleDateString('fr-FR')}</td></tr>)}</tbody></table></div></div></section></main>
}
